name: python-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./python

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          $HOME/.cargo/bin/rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install metadata guardian
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make develop

      - name: Check Python
        run: |
          source venv/bin/activate
          make check-python

      - name: Check Rust
        run: make check-rust

  unit_test:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64:2020-12-31-4928808
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          $HOME/.cargo/bin/rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Enable manylinux Python targets
        run: echo "/opt/python/cp37-cp37m/bin" >> $GITHUB_PATH

      - name: Install metadata guardian
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make develop

      - name: Run unit tests
        run: |
          source venv/bin/activate
          make unit-test

      - name: Build Sphinx documentation
        run: |
          source venv/bin/activate
          make build-documentation