name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./python

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install metadata guardian
        run: make install

      - name: Check Python
        run: make check-python

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Check Rust
        run: make check-rust

  unit_test:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64:2020-12-31-4928808
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          $HOME/.cargo/bin/rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Enable manylinux Python targets
        run: echo "/opt/python/cp36-cp36m/bin" >> $GITHUB_PATH

      - name: Install metadata guardian
        run: make install

      - name: Run unit tests
        run: make unit-test

      - name: Build Sphinx documentation
        run: make build-documentation