name: python-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./python

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install metadata guardian
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make develop

      - name: Check Python
        run: |
          source venv/bin/activate
          make check-python

      - name: Check Rust
        run: make check-rust

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install metadata guardian
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make develop

      - name: Run unit tests
        run: |
          source venv/bin/activate
          make unit-test

      - name: Build Sphinx documentation
        run: |
          source venv/bin/activate
          make build-documentation

  multi-python-running:
    name: Running with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build and install metadata guardian
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          make setup
          maturin develop

      - name: Run metadata guardian
        run: |
          source venv/bin/activate
          python -c 'import metadata_guardian'
