name: Release to PyPI

on:
  push:
    tags: [ 'v*' ]

defaults:
  run:
    working-directory: ./python

jobs:
  validate-git-tag:
    name: Validate the git tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: compare git tag with cargo metadata
        run: |
          TAG=${GITHUB_REF##*/}
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          if [[ "${TAG}" != "v${CURR_VER}" ]]; then
            echo "Cargo metadata has version set to ${CURR_VER}, but got pushed tag ${TAG}."
            exit 1
          fi

  release-pypi-mac-windows:
    needs: validate-git-tag
    name: PyPI release Mac & Windows
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-10.15
          - macOS-11
          - windows-2019
        include:
          - target: x86_64-apple-darwin
            os: macOS-10.15
          - target: aarch64-apple-darwin
            os: macOS-11
          - target: x86_64-pc-windows-msvc
            os: windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup
        run: make setup

      - name: Publish to pypi
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make publish TARGET="${{ matrix.target }}" EXTRA_ARGS="--no-sdist"

  release-pypi-manylinux:
    needs: validate-git-tag
    name: PyPI release manylinux
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            container: quay.io/pypa/manylinux2010_x86_64:2022-03-14-b2cd80b
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
            container: quay.io/pypa/manylinux2014_aarch64:2022-03-14-b2cd80b
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          $HOME/.cargo/bin/rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Enable manylinux Python targets
        run:  echo "/opt/python/cp37-cp37m/bin" >> $GITHUB_PATH
        
      - name: Setup
        run: make setup

      - name: Publish manylinux to pypi (without sdist)
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make publish TARGET="${{ matrix.target }}" EXTRA_ARGS=""


  release-documentation:
    needs: [ validate-git-tag, release-pypi-manylinux, release-pypi-mac-windows ]
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64:2020-12-31-4928808
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
  
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          $HOME/.cargo/bin/rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
  
      - name: Enable manylinux Python targets
        run: echo "/opt/python/cp37-cp37m/bin" >> $GITHUB_PATH
  
      - name: Setup
        run: make setup
  
      - name: Install metadataguardian
        run: make install MATURIN_EXTRA_ARGS="--manylinux off"
      
      - name: Build and Publish Sphinx documentation
        run: |
          echo "Generate the new documentation"
          make build-documentation
          mv docs/build ~/build
          
          echo "Configure git"
          git config --global user.name 'Github Action'
          git config --global user.email 'fvaleye@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
         
          echo "Commit the new changes in the gh-pages"
          git reset --hard HEAD
          git clean -d -fx .
          git checkout gh-pages
          cd ..
          cp -avr ~/build/html/.  ./python
          
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          git status
          git add ./python
          git commit -m "Publish the new documentation for v${CURR_VER}"
          git push origin gh-pages