name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./rust

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Run unit tests
        run: cargo test

      - name: Run Rust coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin -v